# Generated by Django 5.1.4 on 2024-12-18 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
