# Generated by Django 5.1.4 on 2024-12-19 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0006_bankaccount_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='bank',
        ),
    ]
