name: Pipeline CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checando o código
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v2

      - name: Instalar dependências
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install -r requirementes.txt

      - name: Executando Testes
        run: |
          . venv/bin/activate
          python manage.py test
